# ***************************************************************************************************************
# DO NOT MODIFY THIS FILE.  This file may be replaced at anytime without notice in your source code repository.
# This file is part of the standard development framework at Alight. If you have suggested changes, please
# see this page for how to contribute to the Alight Development "Paved Paths":
# https://alightarchitecture.atlassian.net/wiki/x/AYC6GQ
#****************************************************************************************************************

.PHONY: init set-git-config ecr-login update-deps update-perms archive-path build clean-build deploy clean-deploy bounce-app follow-app lint pre-commit pre-commit-diff test coverage push-git check-push push pr hotfix-branch hotfix-pr
.SILENT: init set-git-config ecr-login update-deps update-perms archive-path build clean-build deploy clean-deploy bounce-app follow-app lint pre-commit pre-commit-diff test coverage push-git check-push push pr hotfix-branch hotfix-pr
.ONESHELL:  # run all commands in a single shell, ensuring it runs within a local virtual env
SHELL := /bin/bash
COMMIT_MSG ?= saving work  # Only used for git push, not for creating a PR since PR commit messages will be multiline and generated by commiting.
DEPLOY_DIR := /workspaces/deploy

init:
	sudo $$PYTHON_PATH/bin/pip install --upgrade pip pre-commit commitizen
	$(MAKE) set-git-config
	pre-commit install
	# Only run GitHub CLI login if not already authenticated
	if gh auth status >/dev/null 2>&1; then \
		echo "GitHub CLI already authenticated"; \
	else \
		echo "GitHub CLI not authenticated; starting gh auth login"; \
		gh auth login; \
	fi
	gh workflow run init.yml
	$(MAKE) update-perms

set-git-config:
	@git config --global --add safe.directory "$$(pwd)"
	# Attempt to discover a host gitconfig (common mount points inside containers / codespaces)
	HOST_GITCONFIG=""
	for p in /workspace/.gitconfig /workspaces/.gitconfig /home/codespace/.gitconfig /home/*/.gitconfig /root/.host_gitconfig /root/.gitconfig; do \
		[ -f "$$p" ] && HOST_GITCONFIG="$$p" && break; \
	done; \
	if [ -n "$$HOST_GITCONFIG" ]; then \
		echo "Found candidate host gitconfig at $$HOST_GITCONFIG"; \
		# cat $$HOST_GITCONFIG
		HOST_EMAIL=$$(git config --file $$HOST_GITCONFIG user.email); \
		HOST_NAME=$$(git config --file $$HOST_GITCONFIG user.name); \
	else \
		HOST_EMAIL=""; HOST_NAME=""; \
	fi; \
	if [ -n "$$HOST_EMAIL" ] && [ -n "$$HOST_NAME" ]; then \
		echo "Detected host Git identity: $$HOST_NAME $$HOST_EMAIL"; \
		read -p "Use this identity inside the container? [Y/n]: " accept; \
		# Detects Y/y/Enter response from user
		if [ -z "$$accept" ] || echo "$$accept" | grep -qi '^y'; then \
			git config --global user.email "$$HOST_EMAIL"; \
			git config --global user.name "$$HOST_NAME"; \
			echo "Git user email has been set to: $$HOST_EMAIL"; \
			echo "Git user name has been set to: $$HOST_NAME"; \
			exit 0; \
		fi; \
	fi; \
	echo "Please enter your email for Git configuration: "; \
	read email; \
	git config --global user.email "$$email"; \
	setEmail=$$(git config --global user.email); \
	echo "Git user email has been set to: $$setEmail"; \
	echo "Please enter your name for Git configuration: "; \
	read name; \
	git config --global user.name "$$name"; \
	setName=$$(git config --global user.name); \
	echo "Git user name has been set to: $$setName"

ecr-login:
	aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 755600509381.dkr.ecr.us-east-1.amazonaws.com

update-deps:
	pre-commit autoupdate

update-perms:
	sudo chmod ugo+rwx $(DEPLOY_DIR)

archive-path:
	./gradlew archivePath -q

build:
	./gradlew bootJar --console=plain $(ARGS)

clean-build:
	./gradlew clean bootJar --console=plain $(ARGS)

deploy:
	$(MAKE) update-perms
	$(MAKE) build ARGS="--rerun -PdeployDir=$(DEPLOY_DIR)"
	$(MAKE) bounce-app

clean-deploy:
	$(MAKE) update-perms
	sudo rm -rf $(DEPLOY_DIR)/*
	$(MAKE) clean-build ARGS="-PdeployDir=$(DEPLOY_DIR)"
	$(MAKE) bounce-app

bounce-app:
	project_name=$$(basename $${PWD,,})_devcontainer
	compose_file=.devcontainer/$$(jq -r '.dockerComposeFile' .devcontainer/devcontainer.json)
	docker compose -p $$project_name -f $$compose_file scale appcontainer=0
	docker compose -p $$project_name -f $$compose_file scale appcontainer=1
	$(MAKE) follow-app

follow-app:
	project_name=$$(basename $${PWD,,})_devcontainer
	docker compose -p $$project_name logs appcontainer -f

lint:
	./gradlew lint --console=plain $(ARGS)

pre-commit:
	pre-commit run --all-files

pre-commit-diff:
	pre-commit run --all-files --show-diff-on-failure

test:
	./gradlew test --console=plain $(ARGS)

coverage:
	./gradlew test --console=plain $(ARGS)

push-git:
	@changes=$$(git status --porcelain); \
	if [ -n "$$changes" ]; then \
		git add -A; \
		git commit -m "$(COMMIT_MSG)" || exit 1; \
	fi; \
	BRANCH=$$(git branch --show-current); \
	OUTPUT=$$(git push --set-upstream origin $$BRANCH 2>&1); \
    COMMIT_SHA=$$(git rev-parse --short HEAD); \
	echo "Commit SHA: $$COMMIT_SHA"; \
	./.watch_workflow.sh $$BRANCH "Java App Push" $$COMMIT_SHA; \
	echo 'Showing last 5 runs of the "Java App Push" workflow as FYI ....'; \
	gh run list --workflow "Java App Push" --limit 5

check-push:
	$(MAKE) pre-commit lint coverage

push:
	$(MAKE) check-push push-git

pr:
	rm -f .pr.txt
	cz commit --dry-run --write-message-to-file .pr.txt
	BRANCH="$$(git branch --show-current)"
	BASE="$${BASE_BRANCH:-main}"
	TITLE="$$(head -n 1 .pr.txt)"
	BODY="$$(cat .pr.txt)"
	echo "Creating pull request to merge '$$BRANCH' into '$$BASE', titled '$$TITLE' with body: '$$BODY'"
	gh pr create --base "$$BASE" --head "$$BRANCH" --title "$$TITLE" --body "$$BODY"
	REPO_NAME=$$(basename $$(git rev-parse --show-toplevel))
	COMMIT_SHA=$$(gh api repos/AlightEngineering/$$REPO_NAME/branches/$$BRANCH --jq '.commit.sha')
	./.watch_workflow.sh $$BRANCH "Java App Pull Request" $$COMMIT_SHA
	echo 'Showing last 5 runs of the "Java App Pull Request" workflow as FYI ....'
	gh run list --workflow "Java App Pull Request" --limit 5

hotfix-branch:
	@git fetch --tags --quiet
	@TAGS=($$(git tag -l --sort=-version:refname | head -10));
	[[ $${#TAGS[@]} -gt 0 ]] || { echo "No release tags found."; exit 1; }; \
	echo "Found $${#TAGS[@]} latest tags. Which one needs a fix?"; \
	echo "Or select 'Manual entry' to enter a tag manually."; \
	PS3="Select a tag number: "; \
	COLUMNS=1 && select SELECTED in "$${TAGS[@]}" "Manual entry"; do \
		if [[ "$$SELECTED" == "Manual entry" ]]; then \
		read -p "Enter the release tag: " SELECTED; \
		git tag -l | grep -q "^$$SELECTED$$" || { echo "Tag '$$SELECTED' does not exist."; exit 1; }; \
		fi; \
		[[ -z "$$SELECTED" ]] && { echo "Invalid selection. Aborting."; exit 1; }; \
		break; \
	done; \
	BRANCH=hotfix/$$SELECTED; \
	git branch --list $$BRANCH | grep -q $$BRANCH || git branch $$BRANCH $$SELECTED; \
	git push -u origin $$BRANCH; \
	gh workflow run init.yml --ref $$BRANCH; \
	git checkout $$BRANCH; \
	echo "----------------------------------------------------------------"; \
	echo -e "\033[0;32m✔\033[0m Hotfix branch '$$BRANCH' created, pushed, and checked out!"; \
	echo "To start working, create a bugfix branch off of '$$BRANCH':"; \
	echo "  git checkout -b <your-branch-name>"; \
	echo "----------------------------------------------------------------"

hotfix-pr:
	@HOTFIX_BRANCHES=($$(git for-each-ref --sort=-refname --format='%(refname:short)' refs/remotes/origin/hotfix/ | sed 's/origin\///' | head -10)); \
	if [ $${#HOTFIX_BRANCHES[@]} -eq 0 ]; then echo "No hotfix branches found."; exit 1; fi; \
	echo "Found $${#HOTFIX_BRANCHES[@]} latest hotfix branches. Select the target hotfix branch for your pull request:"; \
	echo "Or select 'Manual entry' to enter a branch manually."; \
	PS3="Select a branch number: "; \
	COLUMNS=1 && select BRANCH in "$${HOTFIX_BRANCHES[@]}" "Manual entry"; do \
		if [[ "$$BRANCH" == "Manual entry" ]]; then \
			read -p "Enter the hotfix branch name: " BRANCH; \
			git branch -r | grep -q "origin/$$BRANCH" || { echo "Branch '$$BRANCH' does not exist."; exit 1; }; \
		fi; \
		if [[ -z "$$BRANCH" ]]; then \
			echo "Invalid selection. Aborting."; \
			exit 1; \
		fi; \
		echo -e "\033[0;36m⚙\033[0m Preparing pull request into '$$BRANCH'\n"; \
		break; \
	done; \
	$(MAKE) pr BASE_BRANCH="$$BRANCH"
